/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkwearRouteImport } from './routes/workwear'
import { Route as WerbetechnikRouteImport } from './routes/werbetechnik'
import { Route as WerbeartikelRouteImport } from './routes/werbeartikel'
import { Route as TrikotRestaurationRouteImport } from './routes/trikot-restauration'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TShirtsRouteImport } from './routes/t-shirts'
import { Route as SportswearRouteImport } from './routes/sportswear'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrintTechniquesRouteImport } from './routes/print-techniques'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PokaleMedaillenRouteImport } from './routes/pokale-medaillen'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as LasergravurRouteImport } from './routes/lasergravur'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as HoodiesRouteImport } from './routes/hoodies'
import { Route as GeschenkeRouteImport } from './routes/geschenke'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExpressRouteImport } from './routes/express'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AufkleberRouteImport } from './routes/aufkleber'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R3dDruckRouteImport } from './routes/3d-druck'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TextilePrintingIndexRouteImport } from './routes/textile-printing.index'
import { Route as PromotionalProductsIndexRouteImport } from './routes/promotional-products.index'
import { Route as PrintingMethodsIndexRouteImport } from './routes/printing-methods.index'
import { Route as TextilePrintingSlugRouteImport } from './routes/textile-printing.$slug'
import { Route as PromotionalProductsSlugRouteImport } from './routes/promotional-products.$slug'
import { Route as PrintingMethodsSlugRouteImport } from './routes/printing-methods.$slug'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'

const WorkwearRoute = WorkwearRouteImport.update({
  id: '/workwear',
  path: '/workwear',
  getParentRoute: () => rootRouteImport,
} as any)
const WerbetechnikRoute = WerbetechnikRouteImport.update({
  id: '/werbetechnik',
  path: '/werbetechnik',
  getParentRoute: () => rootRouteImport,
} as any)
const WerbeartikelRoute = WerbeartikelRouteImport.update({
  id: '/werbeartikel',
  path: '/werbeartikel',
  getParentRoute: () => rootRouteImport,
} as any)
const TrikotRestaurationRoute = TrikotRestaurationRouteImport.update({
  id: '/trikot-restauration',
  path: '/trikot-restauration',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TShirtsRoute = TShirtsRouteImport.update({
  id: '/t-shirts',
  path: '/t-shirts',
  getParentRoute: () => rootRouteImport,
} as any)
const SportswearRoute = SportswearRouteImport.update({
  id: '/sportswear',
  path: '/sportswear',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintTechniquesRoute = PrintTechniquesRouteImport.update({
  id: '/print-techniques',
  path: '/print-techniques',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PokaleMedaillenRoute = PokaleMedaillenRouteImport.update({
  id: '/pokale-medaillen',
  path: '/pokale-medaillen',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const LasergravurRoute = LasergravurRouteImport.update({
  id: '/lasergravur',
  path: '/lasergravur',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const HoodiesRoute = HoodiesRouteImport.update({
  id: '/hoodies',
  path: '/hoodies',
  getParentRoute: () => rootRouteImport,
} as any)
const GeschenkeRoute = GeschenkeRouteImport.update({
  id: '/geschenke',
  path: '/geschenke',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpressRoute = ExpressRouteImport.update({
  id: '/express',
  path: '/express',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AufkleberRoute = AufkleberRouteImport.update({
  id: '/aufkleber',
  path: '/aufkleber',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R3dDruckRoute = R3dDruckRouteImport.update({
  id: '/3d-druck',
  path: '/3d-druck',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TextilePrintingIndexRoute = TextilePrintingIndexRouteImport.update({
  id: '/textile-printing/',
  path: '/textile-printing/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionalProductsIndexRoute =
  PromotionalProductsIndexRouteImport.update({
    id: '/promotional-products/',
    path: '/promotional-products/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrintingMethodsIndexRoute = PrintingMethodsIndexRouteImport.update({
  id: '/printing-methods/',
  path: '/printing-methods/',
  getParentRoute: () => rootRouteImport,
} as any)
const TextilePrintingSlugRoute = TextilePrintingSlugRouteImport.update({
  id: '/textile-printing/$slug',
  path: '/textile-printing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionalProductsSlugRoute = PromotionalProductsSlugRouteImport.update({
  id: '/promotional-products/$slug',
  path: '/promotional-products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintingMethodsSlugRoute = PrintingMethodsSlugRouteImport.update({
  id: '/printing-methods/$slug',
  path: '/printing-methods/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/3d-druck': typeof R3dDruckRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRoute
  '/aufkleber': typeof AufkleberRoute
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/express': typeof ExpressRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/geschenke': typeof GeschenkeRoute
  '/hoodies': typeof HoodiesRoute
  '/imprint': typeof ImprintRoute
  '/lasergravur': typeof LasergravurRoute
  '/leistungen': typeof LeistungenRoute
  '/pokale-medaillen': typeof PokaleMedaillenRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/print-techniques': typeof PrintTechniquesRoute
  '/privacy': typeof PrivacyRoute
  '/sportswear': typeof SportswearRoute
  '/t-shirts': typeof TShirtsRoute
  '/terms': typeof TermsRoute
  '/trikot-restauration': typeof TrikotRestaurationRoute
  '/werbeartikel': typeof WerbeartikelRoute
  '/werbetechnik': typeof WerbetechnikRoute
  '/workwear': typeof WorkwearRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/printing-methods/$slug': typeof PrintingMethodsSlugRoute
  '/promotional-products/$slug': typeof PromotionalProductsSlugRoute
  '/textile-printing/$slug': typeof TextilePrintingSlugRoute
  '/printing-methods/': typeof PrintingMethodsIndexRoute
  '/promotional-products/': typeof PromotionalProductsIndexRoute
  '/textile-printing/': typeof TextilePrintingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/3d-druck': typeof R3dDruckRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRoute
  '/aufkleber': typeof AufkleberRoute
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/express': typeof ExpressRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/geschenke': typeof GeschenkeRoute
  '/hoodies': typeof HoodiesRoute
  '/imprint': typeof ImprintRoute
  '/lasergravur': typeof LasergravurRoute
  '/leistungen': typeof LeistungenRoute
  '/pokale-medaillen': typeof PokaleMedaillenRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/print-techniques': typeof PrintTechniquesRoute
  '/privacy': typeof PrivacyRoute
  '/sportswear': typeof SportswearRoute
  '/t-shirts': typeof TShirtsRoute
  '/terms': typeof TermsRoute
  '/trikot-restauration': typeof TrikotRestaurationRoute
  '/werbeartikel': typeof WerbeartikelRoute
  '/werbetechnik': typeof WerbetechnikRoute
  '/workwear': typeof WorkwearRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/printing-methods/$slug': typeof PrintingMethodsSlugRoute
  '/promotional-products/$slug': typeof PromotionalProductsSlugRoute
  '/textile-printing/$slug': typeof TextilePrintingSlugRoute
  '/printing-methods': typeof PrintingMethodsIndexRoute
  '/promotional-products': typeof PromotionalProductsIndexRoute
  '/textile-printing': typeof TextilePrintingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/3d-druck': typeof R3dDruckRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRoute
  '/aufkleber': typeof AufkleberRoute
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/express': typeof ExpressRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/geschenke': typeof GeschenkeRoute
  '/hoodies': typeof HoodiesRoute
  '/imprint': typeof ImprintRoute
  '/lasergravur': typeof LasergravurRoute
  '/leistungen': typeof LeistungenRoute
  '/pokale-medaillen': typeof PokaleMedaillenRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/print-techniques': typeof PrintTechniquesRoute
  '/privacy': typeof PrivacyRoute
  '/sportswear': typeof SportswearRoute
  '/t-shirts': typeof TShirtsRoute
  '/terms': typeof TermsRoute
  '/trikot-restauration': typeof TrikotRestaurationRoute
  '/werbeartikel': typeof WerbeartikelRoute
  '/werbetechnik': typeof WerbetechnikRoute
  '/workwear': typeof WorkwearRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/printing-methods/$slug': typeof PrintingMethodsSlugRoute
  '/promotional-products/$slug': typeof PromotionalProductsSlugRoute
  '/textile-printing/$slug': typeof TextilePrintingSlugRoute
  '/printing-methods/': typeof PrintingMethodsIndexRoute
  '/promotional-products/': typeof PromotionalProductsIndexRoute
  '/textile-printing/': typeof TextilePrintingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/3d-druck'
    | '/about'
    | '/accessories'
    | '/aufkleber'
    | '/business'
    | '/contact'
    | '/express'
    | '/faq'
    | '/gallery'
    | '/geschenke'
    | '/hoodies'
    | '/imprint'
    | '/lasergravur'
    | '/leistungen'
    | '/pokale-medaillen'
    | '/portfolio'
    | '/print-techniques'
    | '/privacy'
    | '/sportswear'
    | '/t-shirts'
    | '/terms'
    | '/trikot-restauration'
    | '/werbeartikel'
    | '/werbetechnik'
    | '/workwear'
    | '/portfolio/$slug'
    | '/printing-methods/$slug'
    | '/promotional-products/$slug'
    | '/textile-printing/$slug'
    | '/printing-methods/'
    | '/promotional-products/'
    | '/textile-printing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/3d-druck'
    | '/about'
    | '/accessories'
    | '/aufkleber'
    | '/business'
    | '/contact'
    | '/express'
    | '/faq'
    | '/gallery'
    | '/geschenke'
    | '/hoodies'
    | '/imprint'
    | '/lasergravur'
    | '/leistungen'
    | '/pokale-medaillen'
    | '/portfolio'
    | '/print-techniques'
    | '/privacy'
    | '/sportswear'
    | '/t-shirts'
    | '/terms'
    | '/trikot-restauration'
    | '/werbeartikel'
    | '/werbetechnik'
    | '/workwear'
    | '/portfolio/$slug'
    | '/printing-methods/$slug'
    | '/promotional-products/$slug'
    | '/textile-printing/$slug'
    | '/printing-methods'
    | '/promotional-products'
    | '/textile-printing'
  id:
    | '__root__'
    | '/'
    | '/3d-druck'
    | '/about'
    | '/accessories'
    | '/aufkleber'
    | '/business'
    | '/contact'
    | '/express'
    | '/faq'
    | '/gallery'
    | '/geschenke'
    | '/hoodies'
    | '/imprint'
    | '/lasergravur'
    | '/leistungen'
    | '/pokale-medaillen'
    | '/portfolio'
    | '/print-techniques'
    | '/privacy'
    | '/sportswear'
    | '/t-shirts'
    | '/terms'
    | '/trikot-restauration'
    | '/werbeartikel'
    | '/werbetechnik'
    | '/workwear'
    | '/portfolio/$slug'
    | '/printing-methods/$slug'
    | '/promotional-products/$slug'
    | '/textile-printing/$slug'
    | '/printing-methods/'
    | '/promotional-products/'
    | '/textile-printing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R3dDruckRoute: typeof R3dDruckRoute
  AboutRoute: typeof AboutRoute
  AccessoriesRoute: typeof AccessoriesRoute
  AufkleberRoute: typeof AufkleberRoute
  BusinessRoute: typeof BusinessRoute
  ContactRoute: typeof ContactRoute
  ExpressRoute: typeof ExpressRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  GeschenkeRoute: typeof GeschenkeRoute
  HoodiesRoute: typeof HoodiesRoute
  ImprintRoute: typeof ImprintRoute
  LasergravurRoute: typeof LasergravurRoute
  LeistungenRoute: typeof LeistungenRoute
  PokaleMedaillenRoute: typeof PokaleMedaillenRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PrintTechniquesRoute: typeof PrintTechniquesRoute
  PrivacyRoute: typeof PrivacyRoute
  SportswearRoute: typeof SportswearRoute
  TShirtsRoute: typeof TShirtsRoute
  TermsRoute: typeof TermsRoute
  TrikotRestaurationRoute: typeof TrikotRestaurationRoute
  WerbeartikelRoute: typeof WerbeartikelRoute
  WerbetechnikRoute: typeof WerbetechnikRoute
  WorkwearRoute: typeof WorkwearRoute
  PrintingMethodsSlugRoute: typeof PrintingMethodsSlugRoute
  PromotionalProductsSlugRoute: typeof PromotionalProductsSlugRoute
  TextilePrintingSlugRoute: typeof TextilePrintingSlugRoute
  PrintingMethodsIndexRoute: typeof PrintingMethodsIndexRoute
  PromotionalProductsIndexRoute: typeof PromotionalProductsIndexRoute
  TextilePrintingIndexRoute: typeof TextilePrintingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workwear': {
      id: '/workwear'
      path: '/workwear'
      fullPath: '/workwear'
      preLoaderRoute: typeof WorkwearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/werbetechnik': {
      id: '/werbetechnik'
      path: '/werbetechnik'
      fullPath: '/werbetechnik'
      preLoaderRoute: typeof WerbetechnikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/werbeartikel': {
      id: '/werbeartikel'
      path: '/werbeartikel'
      fullPath: '/werbeartikel'
      preLoaderRoute: typeof WerbeartikelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trikot-restauration': {
      id: '/trikot-restauration'
      path: '/trikot-restauration'
      fullPath: '/trikot-restauration'
      preLoaderRoute: typeof TrikotRestaurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t-shirts': {
      id: '/t-shirts'
      path: '/t-shirts'
      fullPath: '/t-shirts'
      preLoaderRoute: typeof TShirtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sportswear': {
      id: '/sportswear'
      path: '/sportswear'
      fullPath: '/sportswear'
      preLoaderRoute: typeof SportswearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-techniques': {
      id: '/print-techniques'
      path: '/print-techniques'
      fullPath: '/print-techniques'
      preLoaderRoute: typeof PrintTechniquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokale-medaillen': {
      id: '/pokale-medaillen'
      path: '/pokale-medaillen'
      fullPath: '/pokale-medaillen'
      preLoaderRoute: typeof PokaleMedaillenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lasergravur': {
      id: '/lasergravur'
      path: '/lasergravur'
      fullPath: '/lasergravur'
      preLoaderRoute: typeof LasergravurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoodies': {
      id: '/hoodies'
      path: '/hoodies'
      fullPath: '/hoodies'
      preLoaderRoute: typeof HoodiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geschenke': {
      id: '/geschenke'
      path: '/geschenke'
      fullPath: '/geschenke'
      preLoaderRoute: typeof GeschenkeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/express': {
      id: '/express'
      path: '/express'
      fullPath: '/express'
      preLoaderRoute: typeof ExpressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aufkleber': {
      id: '/aufkleber'
      path: '/aufkleber'
      fullPath: '/aufkleber'
      preLoaderRoute: typeof AufkleberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3d-druck': {
      id: '/3d-druck'
      path: '/3d-druck'
      fullPath: '/3d-druck'
      preLoaderRoute: typeof R3dDruckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/textile-printing/': {
      id: '/textile-printing/'
      path: '/textile-printing'
      fullPath: '/textile-printing/'
      preLoaderRoute: typeof TextilePrintingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotional-products/': {
      id: '/promotional-products/'
      path: '/promotional-products'
      fullPath: '/promotional-products/'
      preLoaderRoute: typeof PromotionalProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printing-methods/': {
      id: '/printing-methods/'
      path: '/printing-methods'
      fullPath: '/printing-methods/'
      preLoaderRoute: typeof PrintingMethodsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/textile-printing/$slug': {
      id: '/textile-printing/$slug'
      path: '/textile-printing/$slug'
      fullPath: '/textile-printing/$slug'
      preLoaderRoute: typeof TextilePrintingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotional-products/$slug': {
      id: '/promotional-products/$slug'
      path: '/promotional-products/$slug'
      fullPath: '/promotional-products/$slug'
      preLoaderRoute: typeof PromotionalProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printing-methods/$slug': {
      id: '/printing-methods/$slug'
      path: '/printing-methods/$slug'
      fullPath: '/printing-methods/$slug'
      preLoaderRoute: typeof PrintingMethodsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
  }
}

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R3dDruckRoute: R3dDruckRoute,
  AboutRoute: AboutRoute,
  AccessoriesRoute: AccessoriesRoute,
  AufkleberRoute: AufkleberRoute,
  BusinessRoute: BusinessRoute,
  ContactRoute: ContactRoute,
  ExpressRoute: ExpressRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  GeschenkeRoute: GeschenkeRoute,
  HoodiesRoute: HoodiesRoute,
  ImprintRoute: ImprintRoute,
  LasergravurRoute: LasergravurRoute,
  LeistungenRoute: LeistungenRoute,
  PokaleMedaillenRoute: PokaleMedaillenRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  PrintTechniquesRoute: PrintTechniquesRoute,
  PrivacyRoute: PrivacyRoute,
  SportswearRoute: SportswearRoute,
  TShirtsRoute: TShirtsRoute,
  TermsRoute: TermsRoute,
  TrikotRestaurationRoute: TrikotRestaurationRoute,
  WerbeartikelRoute: WerbeartikelRoute,
  WerbetechnikRoute: WerbetechnikRoute,
  WorkwearRoute: WorkwearRoute,
  PrintingMethodsSlugRoute: PrintingMethodsSlugRoute,
  PromotionalProductsSlugRoute: PromotionalProductsSlugRoute,
  TextilePrintingSlugRoute: TextilePrintingSlugRoute,
  PrintingMethodsIndexRoute: PrintingMethodsIndexRoute,
  PromotionalProductsIndexRoute: PromotionalProductsIndexRoute,
  TextilePrintingIndexRoute: TextilePrintingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
